name: Go

on: [push]

env:
  GO_VERSION: '>=1.24.0'

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-24.04-arm
        - macos-latest
        - windows-latest
    steps:

    - uses: actions/checkout@v5

    - uses: actions/setup-go@v6
      with:
        go-version: ${{ env.GO_VERSION }}

    - run: go test ./...

    - run: go build

# based on: github.com/koron-go/_skeleton/.github/workflows/go.yml
# $Hash:3952de744e19b79e8b302bc2ad93637d7b6c53c63caf813f84897781$
